### ISSUE TITLE
No such file or directory: 'config.json'

### ISSUE THREAD

**Issue by andra-pumnea** [noisemix/noisemix#4]
I installed noisemix via pip install and when I try to run it on my dataset I get the following error:

```
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/anaconda3/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/anaconda3/lib/python3.6/site-packages/noisemix/__init__.py", line 4, in <module>
    from noisemix import noise, formats
  File "/home/anaconda3/lib/python3.6/site-packages/noisemix/noise.py", line 57, in <module>
    with open('config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
```
I tried manually creating the adding the file, but I still get the same error. Any idea how to fix this?

**Comment by bittlingmayer** [comment]
The file exists in the `/noisemix/` dir.

How are you running noisemix and from which directory?  Did you `pip install` or did you just `git clone`?

This seems like a relative vs absolute paths issue.
